ДЗ 1
cmbbigis/2024-2-VK-EDU-Frontend-N-Gavrilov pull request #1
Opened 2024-09-26 06:54 UTC by cmbbigis

# Домашнее задание № 1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Написана функция convertBytesToHuman
* Написаны тесты на функцию convertBytesToHuman
* Написана функция correctSentence
* Написана функция nonUniqueElements

2024-09-26 10:02 UTC, sh4rkizz requested changes
давай .idea тоже в .gitignore сунем

2024-09-26 10:02 UTC, sh4rkizz commented on nonUniqueElements.js
> +  return data.filter((item, index, self) => self.indexOf(item) !== self.lastIndexOf(item))
красивый однострочник, мне нравится решение, но сложность `O(N^2)`, что не очень хорошо
как думаешь, можешь в качестве практики реализовать в `O(N)` времени?

2024-09-26 10:02 UTC, sh4rkizz commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(undefined)).toBe(false);
давай расширим тесты некорректного типа данных
дополним, например, Infinity, () => {}, {}, [] и посмотрим, упадет ли

2024-09-26 20:03 UTC, sh4rkizz requested changes
Последнее замечание, честно-честно)

2024-09-26 20:03 UTC, sh4rkizz commented on convertBytesToHuman.js
> +    if (typeof bytes !== 'number' || bytes < 0 || isNaN(bytes) || bytes === Infinity) {
Не покрыт кейс `-Infinity`
Предлагаю воспользоваться малоизвестным методом `isFinite`, который проверяет на то, является ли число конечным

2024-09-27 03:56 UTC, cmbbigis commented on convertBytesToHuman.js
> +    if (typeof bytes !== 'number' || bytes < 0 || isNaN(bytes) || bytes === Infinity) {
Нууу, вообще -Infinity меньше 0, это одним из предыдущих условий покрывается. Но идею из `isFinite` я понял, поправлю)

2024-09-27 11:09 UTC, sh4rkizz approved these changes
lgtm

2024-09-29 13:48 UTC, merged

2024-09-29 13:48 UTC, martinkomitsky commented
12!