Hw10
cmbbigis/2024-2-VK-EDU-Frontend-N-Gavrilov pull request #10
Opened 2024-12-20 17:53 UTC by cmbbigis

# Домашнее задание № 10

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Добавлены стили для страницы авторизации
* Добавлены стили для страницы регистрации
* Добавлены ограничения на переходы по страницам, завязанные на авторизацию
* Добавлена возможность выхода из аккаунта

2024-12-22 12:57 UTC, sh4rkizz commented on react-chat/src/redux/slice.js
> +        },
По идее logout должен тереть токены, текущего пользователя

2024-12-22 12:57 UTC, sh4rkizz commented on react-chat/src/pages/auth/authPage.jsx
> +        debugger
дебаггер забытый

2024-12-22 12:57 UTC, sh4rkizz commented on react-chat/src/components/routes/appRoutes.jsx
> +            }/>
Корректнее делать PublicRoute здесь [такой же отдельный компонент как и PrivateRoute]

2024-12-22 12:57 UTC, sh4rkizz commented on react-chat/src/components/routes/privateRoute.jsx
> +    return (isAuthorized && children);
Не очень хорошо что оно потенциально может null возвращать в данном случае

Корректно было бы, чтобы isAuthorized вычислялся внутри этого компонента по наличию токенов + признаку того, что они не протухли

В JWT токене лежит поле 'exp', которое отражает время протухания 
Предлагаю его доставать из токена и класть в localstorage рядом с токенами

В этом компоненте доставать из localstorage, и проверять сравнивая с текущей датой

2024-12-22 12:57 UTC, sh4rkizz commented on react-chat/src/pages/editProfile/editProfilePage.jsx
> +            dispatch(setCurrentUser(currentUser));
Не хватает всплывашки об успешном изменении профиля

2024-12-22 12:59 UTC, sh4rkizz commented
руками очистил localstorage, зашел на страницу /chats/

<img width="490" alt="изображение" src="https://github.com/user-attachments/assets/627d4cbd-9d5e-4ffc-8a1f-d98ca3c5200e" />

2024-12-22 13:01 UTC, sh4rkizz requested changes
последний коммент сломал все, не могу восстановить

2024-12-22 13:32 UTC, sh4rkizz approved these changes, later dismissed
lgtm !

2024-12-23 18:46 UTC, martinkomitsky approved these changes, later dismissed
7

2024-12-23 18:46 UTC, martinkomitsky approved these changes

2024-12-23 18:47 UTC, merged