Exam
cmbbigis/2024-2-VK-EDU-Frontend-N-Gavrilov pull request #15
Opened 2024-12-23 18:19 UTC by cmbbigis

# Экзамен

Прошу @martinkomitsky или @haseprogram проверить его.

Что было сделано:
* В корневой папке репозитория создать базовое приложение exam с помощью CRA (или vite) по инструкции выше
* Сверстать 2 страницы и необходимые компоненты
* Реализовать перевод с одного языка на другой (нужно сделать так, чтобы можно было выбирать языки из выпадающего списка)
* Реализовать перевод с неизвестного языка (автоопределитель из API)
* Сохранять историю переводов в localStorage
* Использовать Redux
* Использовать React-router для перехода между страницами
* Задеплоить решение, используя GitHub Actions

Стили до конца занятия сделать не успел

2024-12-29 21:02 UTC, martinkomitsky commented
Предварительная оценка: 36

2025-01-02 23:33 UTC, HaseProgram requested changes
Привет, по коду в целом все хорошо. За что взгляд зацепился - отписал в комментариях.

На + 10 баллов предлагаю немного доделать верстку под макет и вынести состояние инпутов из стора.

2025-01-02 23:33 UTC, HaseProgram commented on exam/src/components/TranslateWindow/TranslateWindow.tsx
> +    const { translateTo, translateFrom, textToTranslate, translatedText } = useSelector((state: RootState) => state.slice)
Кажется, что все эти переменные точно стоило оставить локальным стейтом. В редакс можно положить историю (ну как вариант translatedText).

Хранить в глобальном сторе состояние текущих инпутов - не очень хорошая идея.

2025-01-02 23:33 UTC, HaseProgram commented on exam/src/components/TranslateWindow/TranslateWindow.tsx
> +        localStorage.setItem("history", JSON.stringify(history));
Лучше сторонние фичи (как тут - история) выносить в отдельные модули

2025-01-02 23:33 UTC, HaseProgram commented on exam/src/pages/history/HistoryPage.tsx
> +        }
Также, лучше в отдельный импортируемый модуль

2025-01-06 09:25 UTC, cmbbigis commented on exam/src/components/TranslateWindow/TranslateWindow.tsx
> +    const { translateTo, translateFrom, textToTranslate, translatedText } = useSelector((state: RootState) => state.slice)
Хорошо. Было требование прикрутить redux, я прикручивал как мог)

2025-01-12 18:17 UTC, HaseProgram approved these changes
Теперь придраться не к чему, ставлю 46 🎉

2025-01-12 18:17 UTC, merged