Hw2
cmbbigis/2024-2-VK-EDU-Frontend-N-Gavrilov pull request #2
Opened 2024-10-03 13:04 UTC by cmbbigis

# Домашнее задание № 2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Стилизована форма отправки сообщений, в соответствии с [макетом](https://scene.zeplin.io/project/5b9a4b6aae5aa72171a8e5cf/screen/5b9a4b81fc8e9e51e96b6067).
* Установлены иконки [material icons](https://fonts.google.com/icons).
* Сделано так, чтобы по нажатию на кнопку Enter, сообщение сохранялось в localStorage и добавлялось к списку сообщений выше.
* Настроен деплой страницы на [GitHub Pages](https://pages.github.com/).

2024-10-03 13:05 UTC, cmbbigis commented
Почему-то испарились стили при деплое. Почему так произошло я так и не понял. 
Подскажите, пожалуйста, как это можно исправить?

2024-10-05 08:25 UTC, sh4rkizz commented
пробовал в `index.js` сверху дописать `import './index.css';` ?

2024-10-05 09:25 UTC, sh4rkizz requested changes
отписал замечания в лс

2024-10-10 07:54 UTC, cmbbigis commented
> пробовал в `index.js` сверху дописать `import './index.css';` ?

дописал, стили до gh pages всё равно не доехали, скинул видео с результатом в лс

UPD: доехали

2024-10-10 08:15 UTC, cmbbigis commented
> дописал, стили до gh pages всё равно не доехали, скинул видео с результатом в лс
всё таки удалось сделать так, чтобы доехали

2024-10-10 10:05 UTC, sh4rkizz approved these changes
lgtm

2024-10-10 12:56 UTC, martinkomitsky commented
12!

2024-10-10 12:56 UTC, merged