Hw6
cmbbigis/2024-2-VK-EDU-Frontend-N-Gavrilov pull request #6
Opened 2024-11-17 13:22 UTC by cmbbigis

# Домашнее задание № 6

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Настроен рутинг с помощью HashRouter
* Свёрстана страница профиля
* Свёрстана страница редактирования профиля

2024-11-18 19:44 UTC, sh4rkizz requested changes

2024-11-18 19:44 UTC, sh4rkizz commented on react-chat/src/App.js
> +          <Route path='/editProfile/' Component={EditProfilePage}/>
Вся область инпута должна быть кликабельна, сейчас не очень удобно, поскольку тыкать надо в такую область

![изображение](https://github.com/user-attachments/assets/553289cf-5a5f-42b6-a05d-3370d22cb470)

2024-11-18 19:44 UTC, sh4rkizz commented on react-chat/src/App.js
> +          <Route path='/editProfile/' Component={EditProfilePage}/>
Странное разделение на `editProfile` и просто `profile`, по идее, в рамках ДЗ нужен только editProfile

2024-11-18 19:44 UTC, sh4rkizz commented on react-chat/src/App.js
> +          <Route path='/editProfile/' Component={EditProfilePage}/>
Немного не ок, что я могу сделать так)
<img width="727" alt="изображение" src="https://github.com/user-attachments/assets/cc025ec9-3796-4662-b0b8-8f6c1879a507">

2024-11-18 19:44 UTC, sh4rkizz commented on react-chat/src/App.js
> +          <Route path='/editProfile/' Component={EditProfilePage}/>
Стоит разбить это поле на 2
first_name и last_name [имя и фамилия]

упростит переход к бекенду

<img width="365" alt="изображение" src="https://github.com/user-attachments/assets/9d8c1650-2792-45ca-873b-da1a8883bce7">

2024-11-18 19:44 UTC, sh4rkizz commented on react-chat/src/App.js
> +          <Route path='/editProfile/' Component={EditProfilePage}/>
Странно что я не могу задать пустое "имя"
Именно странно, что я не получаю ошибку, а поле просто сбрасывается на предыдущее

По идее должна быть ошибка а-ля "поле обязательно"

2024-11-18 19:44 UTC, sh4rkizz commented on react-chat/src/App.js
> +          <Route path='/editProfile/' Component={EditProfilePage}/>
Хотелось бы иметь какую-нибудь индикацию того, что сохранение успешно: модалка/алерт/текст на странице, появляющийся на 3-5 секунд

2024-11-18 19:44 UTC, sh4rkizz commented on react-chat/src/App.js
> +          <Route path='/editProfile/' Component={EditProfilePage}/>
стоит обработать 404 когда тыкаешься в ссылку, которая не поддерживается твоей разработкой
https://cmbbigis.github.io/2024-2-VK-EDU-Frontend-N-Gavrilov/#/helloworld/
Сейчас получаю просто пустую страницу

2024-11-18 19:44 UTC, sh4rkizz commented on react-chat/src/App.js
> +          <Route path='/editProfile/' Component={EditProfilePage}/>
По идее ты не можешь заставлять пользователя вбивать руками собаку

Если хочешь, чтобы она была в интерфейсе, можешь попробовать воспользоваться псевдоселектором ::before, куда в content передать "@", попробуй поискать сам как это сделать)

<img width="437" alt="изображение" src="https://github.com/user-attachments/assets/152bd50f-d20f-489f-8963-0e4ae250db6f">

2024-11-18 19:44 UTC, sh4rkizz commented on react-chat/src/App.js
> +          <Route path='/editProfile/' Component={EditProfilePage}/>
Еще из UX, корректнее выводить ошибки под полем красным текстом, а не отдельной модалкой
Стоит поправить

2024-11-18 19:44 UTC, sh4rkizz commented on react-chat/src/App.js
> +          <Route path='/editProfile/' Component={EditProfilePage}/>
Крайне советую вместо этого
<img width="747" alt="изображение" src="https://github.com/user-attachments/assets/95968238-a155-4210-aa2e-1b9c6b84c0db">

Воспользоваться такой конструкцией и адаптировать ее под свои нужды
```
const [errors, setErrors] = useState({});
const [data, setData] = useState({});

const handleInputChange = (event) => {
    const name = event.target.name;
    const value = event.target.value;

    setError((prev) => ({ ...prev, [name]: null }));
    setData((prev) => ({ ...prev, [name]: value }));
}

const handleFileChange = (event) => {
    const file = e.target.files[0];
    setData((prev) => ({ ...prev, avatar: file }));
}
```

2024-11-19 06:47 UTC, cmbbigis commented on react-chat/src/App.js
> +          <Route path='/editProfile/' Component={EditProfilePage}/>
> Странное разделение на `editProfile` и просто `profile`, по идее, в рамках ДЗ нужен только editProfile

Мне наоборот кажется странным, что должна быть только страница редактирования, а просто страницы просмотра нет

2024-11-24 17:08 UTC, sh4rkizz approved these changes
lgtm!
правки договорились в 7 дз

2024-11-26 22:02 UTC, HaseProgram commented
Аппрув! 10

2024-11-26 22:02 UTC, merged