Hw7
cmbbigis/2024-2-VK-EDU-Frontend-N-Gavrilov pull request #7
Opened 2024-11-24 17:06 UTC by cmbbigis

# Домашнее задание № 7

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
* Реализован клиент для работы с бэкендом
* Добавлены запросы на регистрацию и авторизацию и простые страницы для них
* Сообщения теперь передаются на бэкенд
* Входящие сообщения получаются из центрифуги
* Новые чаты получаются с помощью центрифуги при появлении в них сообщения
* Имеющиеся API интегрированы в другие компоненты проекта

2024-11-24 17:08 UTC, cmbbigis commented
Правки из шестой дз будут добавлены в ближайшие дни.

Также сейчас не работает добавление аватарки. Работа с картинками планируется в восьмой дз, планирую исправить это там

2024-11-25 18:00 UTC, cmbbigis commented
Внезапно правками из 6 дз даже починил аватарки

2024-11-25 20:48 UTC, sh4rkizz requested changes

2024-11-25 20:48 UTC, sh4rkizz commented on react-chat/src/utils/backendClient.js
> +}
Казалось бы, ошибка корректная, но отображается пустой алерт

ошибки полей с бекенда нужно под полем отрисовывать и сбрасывать при вводе в это поле

<img width="448" alt="изображение" src="https://github.com/user-attachments/assets/03c68ea4-7de2-4809-9296-84c301cb7a90">

<img width="507" alt="изображение" src="https://github.com/user-attachments/assets/a678f774-4e66-42dd-82cf-7823068726b1">

2024-11-25 20:48 UTC, sh4rkizz commented on react-chat/src/utils/backendClient.js
> +}
Пароль здесь и на странице реги стоит делать звездочками [атрибут `type` у `input`]

<img width="295" alt="изображение" src="https://github.com/user-attachments/assets/c2518efb-26fb-4c61-a546-16c263644430">

2024-11-25 20:48 UTC, sh4rkizz commented on react-chat/src/utils/backendClient.js
> +}
аналогично стоит обработать ошибки профиля
здесь ошибка - username: ['уже существует'], такое отображается под полем

<img width="435" alt="изображение" src="https://github.com/user-attachments/assets/e2c30f5c-82ed-4c87-90c7-e4ac3e1b7fb2">

2024-11-25 20:48 UTC, sh4rkizz commented on react-chat/src/utils/backendClient.js
> +}
Есть ошибки которые невозможно отрисовать под полем [например когда ты пытаешься создать чат с пользователем, чат с которым уже создан]

Эти ошибки нужно отрисовывать попапами
Для этого дела крайне рекомендую либу react-tostify
https://www.npmjs.com/package/react-toastify

Всем ребятам посоветовал, вкрутили, радуются жизни

2024-11-25 20:48 UTC, sh4rkizz commented on react-chat/src/utils/backendClient.js
> +}
Каждый чат в списке чатов это ссылка - это корректно

Однако, стоит указывать абсолютный href, а не относительный
Из-за этого выдается 404 при попытке перейти к такому чату [потому что chats/chat/]

Абсолютный урл в этом случае отличается тем, что начинается со `/`

<img width="194" alt="изображение" src="https://github.com/user-attachments/assets/11f263d4-d360-45b0-9699-441551ec60f6">

2024-11-25 20:48 UTC, sh4rkizz commented on react-chat/src/utils/backendClient.js
> +}
Сейчас когда пытаешься создать чат - вынужден играть в рулетку - попадать в username

Максимально корректно здесь было бы увидеть поле ввода, куда я могу ввести ник или фио желаемого пользователя [бекенд для этого существует]

После чего выбрать его/их из списка и нажать кнопку "создать чат"

Минимальным требованием хотя бы сделай селект)

<img width="480" alt="изображение" src="https://github.com/user-attachments/assets/20b23a92-5950-43f9-ba9a-bf26c016d155">

2024-11-25 20:48 UTC, sh4rkizz commented on react-chat/src/utils/backendClient.js
> +}
В чем суть, сейчас у тебя в data в профиле кладется avatar как строка [путь до файла на бекенде]
При попытке сохранить профиль, эту ссылку ты пытаешься отдать обратно

Так делать нельзя [бекенд вот и ругается]
Файл стоит отдельно включать в formData, только если это новый файл

<img width="661" alt="изображение" src="https://github.com/user-attachments/assets/5ff9a2f9-0e10-4280-8a06-6ea5cb0e4680">

2024-11-25 20:48 UTC, sh4rkizz commented on react-chat/src/utils/backendClient.js
> +}
не нужно страдать с блобами для вывода на фронт, достаточно передать то, что лежит в поле avatar [если эта фотка пришла как путь до файла на бекенде]

Иначе сейчас, реально имеющаяся аватарка будет ломаться

<img width="625" alt="изображение" src="https://github.com/user-attachments/assets/fdd9128b-4394-4700-af25-ac87648f7fbd">

<img width="359" alt="изображение" src="https://github.com/user-attachments/assets/298aed77-9852-47e4-aa83-8b1fc30fc103">

2024-11-28 18:37 UTC, sh4rkizz commented
сейчас подломан список чатов, не получается открыть, если там имеются чаты без text или без last_message

<img width="701" alt="изображение" src="https://github.com/user-attachments/assets/554346ce-51b7-4774-ba9b-bfdab78c0be9">

2024-12-06 09:12 UTC, sh4rkizz approved these changes
LGTM !

2024-12-06 22:18 UTC, HaseProgram commented
Зачтено, 7!

2024-12-06 22:18 UTC, merged